-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/HDLRx/full_rx_ip_src_Normalize_denominator_block.vhd
-- Created: 2024-08-10 11:14:30
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: full_rx_ip_src_Normalize_denominator_block
-- Source Path: HDLRx/full_rx/rx_demodulator_full/ofdm_symbol_sync/m_cox/Real Divide HDL Optimized/ForEach - Real 
-- Divide/Normalize denominato
-- Hierarchy Level: 6
-- Model version: 1.14
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY full_rx_ip_src_Normalize_denominator_block IS
  PORT( clk                               :   IN    std_logic;
        reset_x                           :   IN    std_logic;
        enb_1_2_0                         :   IN    std_logic;
        u                                 :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En24
        validIn                           :   IN    std_logic;
        x                                 :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En30
        e                                 :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
        isNegative                        :   OUT   std_logic;
        validOut                          :   OUT   std_logic
        );
END full_rx_ip_src_Normalize_denominator_block;


ARCHITECTURE rtl OF full_rx_ip_src_Normalize_denominator_block IS

  -- Component Declarations
  COMPONENT full_rx_ip_src_positiveRealNormalizer_block2
    PORT( clk                             :   IN    std_logic;
          reset_x                         :   IN    std_logic;
          enb_1_2_0                       :   IN    std_logic;
          u                               :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En24
          validIn                         :   IN    std_logic;
          x                               :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En30
          e                               :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
          isNegative                      :   OUT   std_logic;
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : full_rx_ip_src_positiveRealNormalizer_block2
    USE ENTITY work.full_rx_ip_src_positiveRealNormalizer_block2(rtl);

  -- Signals
  SIGNAL x_tmp                            : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL e_tmp                            : std_logic_vector(31 DOWNTO 0);  -- ufix32

BEGIN
  u_positiveRealNormalizer : full_rx_ip_src_positiveRealNormalizer_block2
    PORT MAP( clk => clk,
              reset_x => reset_x,
              enb_1_2_0 => enb_1_2_0,
              u => u,  -- sfix32_En24
              validIn => validIn,
              x => x_tmp,  -- sfix32_En30
              e => e_tmp,  -- int32
              isNegative => isNegative,
              validOut => validOut
              );

  x <= x_tmp;

  e <= e_tmp;

END rtl;

