-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/HDLRx/full_rx_ip_src_batid_to_bits_per_subcarrier.vhd
-- Created: 2024-08-10 11:14:31
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: full_rx_ip_src_batid_to_bits_per_subcarrier
-- Source Path: HDLRx/full_rx/batid_to_bits_per_subcarrier
-- Hierarchy Level: 1
-- Model version: 1.14
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY full_rx_ip_src_batid_to_bits_per_subcarrier IS
  PORT( bat_id                            :   IN    std_logic_vector(4 DOWNTO 0);  -- ufix1 [5]
        bits_per_subcarrier               :   OUT   std_logic_vector(3 DOWNTO 0)  -- ufix4
        );
END full_rx_ip_src_batid_to_bits_per_subcarrier;


ARCHITECTURE rtl OF full_rx_ip_src_batid_to_bits_per_subcarrier IS

  -- Signals
  SIGNAL bat_id_3                         : std_logic;  -- ufix1
  SIGNAL bat_id_2                         : std_logic;  -- ufix1
  SIGNAL bat_id_1                         : std_logic;  -- ufix1
  SIGNAL bat_id_0                         : std_logic;  -- ufix1
  SIGNAL y                                : unsigned(3 DOWNTO 0);  -- ufix4

BEGIN
  -- Remember that "bat_id" is LSB first.
  -- De momento, el valor de BATID va a coincidir con el valor de la cantidad de bits por subcarrier.

  bat_id_3 <= bat_id(3);

  bat_id_2 <= bat_id(2);

  bat_id_1 <= bat_id(1);

  bat_id_0 <= bat_id(0);

  y <= unsigned'(bat_id_3 & bat_id_2 & bat_id_1 & bat_id_0);

  bits_per_subcarrier <= std_logic_vector(y);

END rtl;

