-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/HDLModulatorFull/full_ofdm_modulator_ip_src_symbolFormation.vhd
-- Created: 2024-09-01 12:13:06
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: full_ofdm_modulator_ip_src_symbolFormation
-- Source Path: 
-- Hierarchy Level: 3
-- Model version: 1.43
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.full_ofdm_modulator_ip_src_full_ofdm_modulator_pac.ALL;

ENTITY full_ofdm_modulator_ip_src_symbolFormation IS
  PORT( clk                               :   IN    std_logic;
        reset_x                           :   IN    std_logic;
        enb_1_2_0                         :   IN    std_logic;
        varargin_1_re                     :   IN    std_logic_vector(11 DOWNTO 0);  -- sfix12_En10
        varargin_1_im                     :   IN    std_logic_vector(11 DOWNTO 0);  -- sfix12_En10
        varargin_2                        :   IN    std_logic;
        varargin_3                        :   IN    std_logic_vector(13 DOWNTO 0);  -- ufix14
        varargin_4                        :   IN    std_logic_vector(13 DOWNTO 0);  -- ufix14
        varargin_5                        :   IN    std_logic_vector(13 DOWNTO 0);  -- ufix14
        varargin_6                        :   IN    std_logic_vector(13 DOWNTO 0);  -- ufix14
        varargout_1_re                    :   OUT   std_logic_vector(11 DOWNTO 0);  -- sfix12_En10
        varargout_1_im                    :   OUT   std_logic_vector(11 DOWNTO 0);  -- sfix12_En10
        varargout_2                       :   OUT   std_logic;
        varargout_3                       :   OUT   std_logic_vector(13 DOWNTO 0);  -- ufix14
        varargout_4                       :   OUT   std_logic_vector(13 DOWNTO 0)  -- ufix14
        );
END full_ofdm_modulator_ip_src_symbolFormation;


ARCHITECTURE rtl OF full_ofdm_modulator_ip_src_symbolFormation IS

  -- Component Declarations
  COMPONENT full_ofdm_modulator_ip_src_SimpleDualPortRAM_generic
    GENERIC( AddrWidth                    : integer;
             DataWidth                    : integer
             );
    PORT( clk                             :   IN    std_logic;
          enb_1_2_0                       :   IN    std_logic;
          wr_din_re                       :   IN    std_logic_vector(DataWidth - 1 DOWNTO 0);  -- generic width
          wr_din_im                       :   IN    std_logic_vector(DataWidth - 1 DOWNTO 0);  -- generic width
          wr_addr                         :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
          wr_en                           :   IN    std_logic;
          rd_addr                         :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
          dout_re                         :   OUT   std_logic_vector(DataWidth - 1 DOWNTO 0);  -- generic width
          dout_im                         :   OUT   std_logic_vector(DataWidth - 1 DOWNTO 0)  -- generic width
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : full_ofdm_modulator_ip_src_SimpleDualPortRAM_generic
    USE ENTITY work.full_ofdm_modulator_ip_src_SimpleDualPortRAM_generic(rtl);

  -- Signals
  SIGNAL tmp                              : std_logic;
  SIGNAL obj_symbolFormationObj_validInReg_reg_reg : std_logic_vector(2 DOWNTO 0);  -- ufix1 [3]
  SIGNAL obj_symbolFormationObj_validInReg : std_logic;
  SIGNAL obj_symbolFormationObj_inCount   : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL varargin_3_unsigned              : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL tmp_1                            : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_FFTLenRegDelay2 : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_FFTLenRegDelay1 : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL varargin_5_unsigned              : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL tmp_2                            : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL varargin_6_unsigned              : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL tmp_3                            : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_4                            : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_sumLgRg   : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_insertDC  : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_5                            : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_sumLgRgDC : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_6                            : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_numDataSc : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_7                            : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_inCount_1 : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL s                                : std_logic;
  SIGNAL obj_symbolFormationObj_numDataScMinusVecLen : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_8                            : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_9                            : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_10                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL a0                               : std_logic;
  SIGNAL tmp_11                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_12                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_RAM2WriteSelect : std_logic;
  SIGNAL tmp_13                           : std_logic;
  SIGNAL tmp_14                           : std_logic;
  SIGNAL tmp_15                           : std_logic;
  SIGNAL s_1                              : std_logic;
  SIGNAL out_rsvd                         : std_logic;
  SIGNAL out_rsvd_1                       : std_logic;
  SIGNAL tmp_16                           : std_logic;
  SIGNAL obj_symbolFormationObj_writeEnbRAM1 : std_logic;
  SIGNAL s_2                              : std_logic;
  SIGNAL out_rsvd_2                       : std_logic;
  SIGNAL out_rsvd_3                       : std_logic;
  SIGNAL tmp_17                           : std_logic;
  SIGNAL obj_symbolFormationObj_writeEnbRAM2 : std_logic;
  SIGNAL obj_symbolFormationObj_sym1Done  : std_logic;
  SIGNAL obj_symbolFormationObj_inCountReg : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL a0_1                             : std_logic;
  SIGNAL obj_symbolFormationObj_sym1Done_1 : std_logic;
  SIGNAL obj_symbolFormationObj_sym2Done  : std_logic;
  SIGNAL a0_2                             : std_logic;
  SIGNAL obj_symbolFormationObj_sym2Done_1 : std_logic;
  SIGNAL obj_symbolFormationObj_outCount  : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_FFTLenReg : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_18                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_FFTLenMinusVecLen : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_19                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_20                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_startSymbForm : std_logic;
  SIGNAL obj_symbolFormationObj_startSymbForm_1 : std_logic;
  SIGNAL tmp_21                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_FFTLenMinusVecLenReg : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_outCount_1 : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL s_3                              : std_logic;
  SIGNAL tmp_22                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL a0_3                             : std_logic;
  SIGNAL tmp_23                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_startSymbForm_2 : std_logic;
  SIGNAL tmp_24                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_25                           : std_logic;
  SIGNAL tmp_26                           : std_logic;
  SIGNAL tmp_27                           : std_logic;
  SIGNAL tmp_28                           : std_logic;
  SIGNAL obj_symbolFormationObj_sym2Done_2 : std_logic;
  SIGNAL tmp_29                           : std_logic;
  SIGNAL tmp_30                           : std_logic;
  SIGNAL tmp_31                           : std_logic;
  SIGNAL obj_symbolFormationObj_sym1Done_2 : std_logic;
  SIGNAL tmp_32                           : std_logic;
  SIGNAL s_4                              : std_logic;
  SIGNAL tmp_33                           : std_logic;
  SIGNAL tmp_34                           : std_logic;
  SIGNAL tmp_35                           : std_logic;
  SIGNAL tmp_36                           : std_logic;
  SIGNAL tmp_37                           : std_logic;
  SIGNAL obj_symbolFormationObj_startSymbFormReg : std_logic;
  SIGNAL obj_symbolFormationObj_startSymbFormReg2_reg_reg : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL obj_symbolFormationObj_startSymbFormReg2 : std_logic;
  SIGNAL obj_symbolFormationObj_sendOutput : std_logic;
  SIGNAL obj_symbolFormationObj_sendOutput_1 : std_logic;
  SIGNAL tmp_38                           : std_logic;
  SIGNAL obj_symbolFormationObj_sendOutput_2 : std_logic;
  SIGNAL obj_symbolFormationObj_dataOutReg_re : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL obj_symbolFormationObj_dataOutReg_im : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL obj_symbolFormationObj_outCountReg1_reg_reg : vector_of_unsigned9(0 TO 1);  -- ufix9 [2]
  SIGNAL obj_symbolFormationObj_outCountReg1 : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_outCountReg2 : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_numLgScRegDelay2 : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_numLgScRegDelay1 : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_numLgScReg : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_numLgScSampled : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_39                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_40                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_41                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_numLgScSampledReg : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_numLgScOutReg1 : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_numLgScOutReg2 : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_numLgScOutReg3 : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL a0_4                             : std_logic;
  SIGNAL tmp_42                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_43                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_44                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_45                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL s_5                              : std_logic;
  SIGNAL obj_symbolFormationObj_FFTSampled : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_46                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_47                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_numRgScRegDelay2 : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_numRgScRegDelay1 : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_numRgScReg : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_numRgScSampled : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_48                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_49                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_50                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_51                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_FFTLenMinusNumRgScReg : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL a0_5                             : std_logic;
  SIGNAL obj_symbolFormationObj_numLgScCountReg : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_numLgScCountReg_1 : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_numLgScCount : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_52                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_53                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_54                           : std_logic;
  SIGNAL tmp_55                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_56                           : std_logic;
  SIGNAL tmp_57                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_58                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_59                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_numLgScCountReg_2 : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_numSampLeft : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_numSampLeft_1 : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_60                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_insertDC_1 : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL s_6                              : std_logic;
  SIGNAL tmp_61                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_62                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_63                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_numSampLeft_2 : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_64                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_65                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_66                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_maxLimitForDataReg : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_maxLimitForDataReg2_reg_reg : vector_of_unsigned9(0 TO 1);  -- ufix9 [2]
  SIGNAL obj_symbolFormationObj_maxLimitForDataReg2 : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL s_7                              : std_logic;
  SIGNAL out_rsvd_4                       : std_logic;
  SIGNAL out_rsvd_5                       : std_logic;
  SIGNAL out_rsvd_6                       : std_logic;
  SIGNAL tmp_67                           : std_logic;
  SIGNAL tmp_68                           : std_logic;
  SIGNAL obj_symbolFormationObj_enbDataPlacing : std_logic;
  SIGNAL obj_symbolFormationObj_sendDC    : std_logic;
  SIGNAL tmp_69                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_FFTLenBy2 : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_70                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_FFTLenBy2Reg : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_FFTLenBy2Reg1 : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_FFTLenBy2Reg2 : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_FFTLenBy2Reg3 : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL a0_6                             : std_logic;
  SIGNAL obj_symbolFormationObj_sendDC_1  : std_logic;
  SIGNAL obj_symbolFormationObj_sendDC_2  : std_logic;
  SIGNAL tmp_71                           : std_logic;
  SIGNAL tmp_72                           : std_logic;
  SIGNAL obj_symbolFormationObj_sendDC_3  : std_logic;
  SIGNAL tmp_73                           : std_logic;
  SIGNAL obj_symbolFormationObj_sendDC_4  : std_logic;
  SIGNAL tmp_74                           : std_logic;
  SIGNAL obj_symbolFormationObj_FFTLenMinusVecLenReg1 : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_FFTLenMinusVecLenReg2 : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_FFTLenMinusVecLenReg3 : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL a0_7                             : std_logic;
  SIGNAL obj_symbolFormationObj_prevVecSamples : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_prevVecSamples_1 : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_numLgScCountReg2_reg_reg : vector_of_unsigned9(0 TO 1);  -- ufix9 [2]
  SIGNAL obj_symbolFormationObj_numLgScCountReg2 : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_numLgScCountReg3 : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL a0_8                             : std_logic;
  SIGNAL obj_symbolFormationObj_prevVecSamples_2 : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_75                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_prevVecSamples_3 : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_prevVecSamples_4 : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_76                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_77                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_78                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_79                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_80                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_81                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL s_8                              : std_logic;
  SIGNAL obj_symbolFormationObj_dataVec1Samples : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_dataVec1Samples_1 : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_82                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_83                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_84                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_dataVec1Samples_2 : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_85                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL s_9                              : std_logic;
  SIGNAL obj_symbolFormationObj_dataVec2_re : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL obj_symbolFormationObj_dataVec2_im : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL s_10                             : std_logic;
  SIGNAL s_11                             : std_logic;
  SIGNAL out_rsvd_7                       : std_logic;
  SIGNAL out_rsvd_8                       : std_logic;
  SIGNAL out_rsvd_9                       : std_logic;
  SIGNAL tmp_86                           : std_logic;
  SIGNAL tmp_87                           : std_logic;
  SIGNAL obj_symbolFormationObj_startRead : std_logic;
  SIGNAL obj_symbolFormationObj_startRead_1 : std_logic;
  SIGNAL tmp_88                           : std_logic;
  SIGNAL obj_symbolFormationObj_startRead_2 : std_logic;
  SIGNAL obj_symbolFormationObj_startRead_3 : std_logic;
  SIGNAL tmp_89                           : std_logic;
  SIGNAL obj_symbolFormationObj_startRead_4 : std_logic;
  SIGNAL tmp_90                           : std_logic;
  SIGNAL tmp_91                           : std_logic;
  SIGNAL obj_symbolFormationObj_startRead_5 : std_logic;
  SIGNAL tmp_92                           : std_logic;
  SIGNAL obj_symbolFormationObj_startReadFromRAM : std_logic;
  SIGNAL varargin_4_unsigned              : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL tmp_93                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_CPLenRegDelay2 : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_CPLenRegDelay1 : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_CPLenReg  : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_CPSampled : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_94                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_95                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_96                           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_CPSampledReg : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_97                           : std_logic;
  SIGNAL obj_symbolFormationObj_selectRAM : std_logic;
  SIGNAL tmp_98                           : std_logic;
  SIGNAL tmp_99                           : std_logic;
  SIGNAL tmp_100                          : std_logic;
  SIGNAL obj_symbolFormationObj_selectRAMReg : std_logic;
  SIGNAL obj_symbolFormationObj_selectRAMReg1 : std_logic;
  SIGNAL tmp_101                          : std_logic;
  SIGNAL obj_symbolFormationObj_RAM2ReadSelect : std_logic;
  SIGNAL s_12                             : std_logic;
  SIGNAL varargin_1_re_signed             : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL varargin_1_im_signed             : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL obj_symbolFormationObj_dataInReg1_reg_reg_re : vector_of_signed12(0 TO 3);  -- sfix12_En10 [4]
  SIGNAL obj_symbolFormationObj_dataInReg1_reg_reg_im : vector_of_signed12(0 TO 3);  -- sfix12_En10 [4]
  SIGNAL obj_symbolFormationObj_dataInReg1_re : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL obj_symbolFormationObj_dataInReg1_im : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL obj_symbolFormationObj_writeAddrRAM2 : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL obj_symbolFormationObj_writeAddrRAM2_1 : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL tmp_102                          : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL tmp_103                          : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL tmp_104                          : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL tmp_105                          : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL s_13                             : std_logic;
  SIGNAL obj_symbolFormationObj_readCount : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_106                          : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_numDataScMinusVecLenReg : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_readCount_1 : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_107                          : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL a0_9                             : std_logic;
  SIGNAL tmp_108                          : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL tmp_109                          : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_readAddr  : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL obj_symbolFormationObj_readAddr_1 : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL tmp_110                          : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL tmp_111                          : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL tmp_112                          : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL varargout_1_re_1                 : std_logic_vector(11 DOWNTO 0);  -- ufix12
  SIGNAL varargout_1_im_1                 : std_logic_vector(11 DOWNTO 0);  -- ufix12
  SIGNAL varargout_1_re_signed            : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL varargout_1_im_signed            : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL obj_symbolFormationObj_writeAddrRAM1 : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL obj_symbolFormationObj_writeAddrRAM1_1 : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL tmp_113                          : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL tmp_114                          : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL tmp_115                          : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL varargout_1_re_2                 : std_logic_vector(11 DOWNTO 0);  -- ufix12
  SIGNAL varargout_1_im_2                 : std_logic_vector(11 DOWNTO 0);  -- ufix12
  SIGNAL varargout_1_re_signed_1          : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL varargout_1_im_signed_1          : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL tmp_re                           : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL tmp_im                           : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL obj_symbolFormationObj_dataOutRAM_re : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL obj_symbolFormationObj_dataOutRAM_im : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL tmp_re_1                         : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL tmp_im_1                         : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL tmp_re_2                         : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL tmp_im_2                         : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL obj_symbolFormationObj_dataVec2_re_1 : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL obj_symbolFormationObj_dataVec2_im_1 : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL obj_symbolFormationObj_dataVec2_re_2 : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL obj_symbolFormationObj_dataVec2_im_2 : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL tmp_re_3                         : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL tmp_im_3                         : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL tmp_re_4                         : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL tmp_im_4                         : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL tmp_re_5                         : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL tmp_im_5                         : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL obj_symbolFormationObj_dataVec2_re_3 : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL obj_symbolFormationObj_dataVec2_im_3 : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL tmp_re_6                         : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL tmp_im_6                         : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL obj_symbolFormationObj_prevVecData_re : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL obj_symbolFormationObj_prevVecData_im : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL tmp_re_7                         : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL tmp_im_7                         : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL obj_symbolFormationObj_prevVecData_re_1 : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL obj_symbolFormationObj_prevVecData_im_1 : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL tmp_re_8                         : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL tmp_im_8                         : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL tmp_re_9                         : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL tmp_im_9                         : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL obj_symbolFormationObj_prevVecData_re_2 : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL obj_symbolFormationObj_prevVecData_im_2 : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL tmp_re_10                        : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL tmp_im_10                        : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL tmp_re_11                        : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL tmp_im_11                        : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL obj_symbolFormationObj_dataVec1_re : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL obj_symbolFormationObj_dataVec1_im : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL obj_symbolFormationObj_dataVec1_re_1 : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL obj_symbolFormationObj_dataVec1_im_1 : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL tmp_re_12                        : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL tmp_im_12                        : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL obj_symbolFormationObj_dataVec1_re_2 : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL obj_symbolFormationObj_dataVec1_im_2 : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL tmp_re_13                        : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL tmp_im_13                        : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL tmp_re_14                        : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL tmp_im_14                        : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL obj_symbolFormationObj_dataVec1_re_3 : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL obj_symbolFormationObj_dataVec1_im_3 : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL tmp_re_15                        : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL tmp_im_15                        : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL tmp_re_16                        : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL tmp_im_16                        : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL obj_symbolFormationObj_dataOutReg_re_1 : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL obj_symbolFormationObj_dataOutReg_im_1 : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL tmp_re_17                        : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL tmp_im_17                        : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL tmp_re_18                        : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL tmp_im_18                        : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL obj_symbolFormationObj_dataOut_reg_reg_re : vector_of_signed12(0 TO 1);  -- sfix12_En10 [2]
  SIGNAL obj_symbolFormationObj_dataOut_reg_reg_im : vector_of_signed12(0 TO 1);  -- sfix12_En10 [2]
  SIGNAL obj_symbolFormationObj_dataOut_re : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL obj_symbolFormationObj_dataOut_im : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL obj_symbolFormationObj_validOutReg : std_logic;
  SIGNAL obj_symbolFormationObj_validOutReg_1 : std_logic;
  SIGNAL tmp_116                          : std_logic;
  SIGNAL obj_symbolFormationObj_validOut_reg_reg : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL obj_symbolFormationObj_validOut  : std_logic;
  SIGNAL tmp_117                          : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_FFTSampledReg : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_FFTLenOutReg1 : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_FFTLenOutReg2 : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_FFTLenOut : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL varargout_3_tmp                  : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL obj_symbolFormationObj_CPLenOutReg1 : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_CPLenOutReg2 : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL obj_symbolFormationObj_CPLenOut  : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL varargout_4_tmp                  : unsigned(13 DOWNTO 0);  -- ufix14

BEGIN
  u_simpleDualPortRam : full_ofdm_modulator_ip_src_SimpleDualPortRAM_generic
    GENERIC MAP( AddrWidth => 10,
                 DataWidth => 12
                 )
    PORT MAP( clk => clk,
              enb_1_2_0 => enb_1_2_0,
              wr_din_re => std_logic_vector(obj_symbolFormationObj_dataInReg1_re),
              wr_din_im => std_logic_vector(obj_symbolFormationObj_dataInReg1_im),
              wr_addr => std_logic_vector(obj_symbolFormationObj_writeAddrRAM2_1),
              wr_en => obj_symbolFormationObj_writeEnbRAM2,
              rd_addr => std_logic_vector(obj_symbolFormationObj_readAddr_1),
              dout_re => varargout_1_re_1,
              dout_im => varargout_1_im_1
              );

  u_simpleDualPortRam_generic : full_ofdm_modulator_ip_src_SimpleDualPortRAM_generic
    GENERIC MAP( AddrWidth => 10,
                 DataWidth => 12
                 )
    PORT MAP( clk => clk,
              enb_1_2_0 => enb_1_2_0,
              wr_din_re => std_logic_vector(obj_symbolFormationObj_dataInReg1_re),
              wr_din_im => std_logic_vector(obj_symbolFormationObj_dataInReg1_im),
              wr_addr => std_logic_vector(obj_symbolFormationObj_writeAddrRAM1_1),
              wr_en => obj_symbolFormationObj_writeEnbRAM1,
              rd_addr => std_logic_vector(obj_symbolFormationObj_readAddr_1),
              dout_re => varargout_1_re_2,
              dout_im => varargout_1_im_2
              );

  tmp <= varargin_2;

  obj_symbolFormationObj_validInReg_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_validInReg_reg_reg <= (OTHERS => '0');
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_validInReg_reg_reg(0) <= tmp;
        obj_symbolFormationObj_validInReg_reg_reg(2 DOWNTO 1) <= obj_symbolFormationObj_validInReg_reg_reg(1 DOWNTO 0);
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_validInReg_reg_process;

  obj_symbolFormationObj_validInReg <= obj_symbolFormationObj_validInReg_reg_reg(2);

  obj_symbolFormationObj_inCount <= to_unsigned(16#000#, 9);

  varargin_3_unsigned <= unsigned(varargin_3);

  tmp_1 <= varargin_3_unsigned(8 DOWNTO 0);

  obj_symbolFormationObj_FFTLenRegDelay2_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_FFTLenRegDelay2 <= to_unsigned(16#040#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_FFTLenRegDelay2 <= tmp_1;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_FFTLenRegDelay2_reg_process;


  obj_symbolFormationObj_FFTLenRegDelay1_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_FFTLenRegDelay1 <= to_unsigned(16#040#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_FFTLenRegDelay1 <= obj_symbolFormationObj_FFTLenRegDelay2;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_FFTLenRegDelay1_reg_process;


  varargin_5_unsigned <= unsigned(varargin_5);

  tmp_2 <= varargin_5_unsigned(8 DOWNTO 0);

  varargin_6_unsigned <= unsigned(varargin_6);

  tmp_3 <= varargin_6_unsigned(8 DOWNTO 0);

  tmp_4 <= tmp_2 + tmp_3;

  obj_symbolFormationObj_sumLgRg_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_sumLgRg <= to_unsigned(16#00B#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_sumLgRg <= tmp_4;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_sumLgRg_reg_process;


  obj_symbolFormationObj_insertDC <= to_unsigned(16#000#, 9);

  tmp_5 <= obj_symbolFormationObj_sumLgRg + obj_symbolFormationObj_insertDC;

  obj_symbolFormationObj_sumLgRgDC_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_sumLgRgDC <= to_unsigned(16#00B#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_sumLgRgDC <= tmp_5;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_sumLgRgDC_reg_process;


  tmp_6 <= obj_symbolFormationObj_FFTLenRegDelay1 - obj_symbolFormationObj_sumLgRgDC;

  obj_symbolFormationObj_numDataSc_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_numDataSc <= to_unsigned(16#040#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_numDataSc <= tmp_6;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_numDataSc_reg_process;


  tmp_7 <= obj_symbolFormationObj_numDataSc - to_unsigned(16#001#, 9);

  
  s <= '1' WHEN obj_symbolFormationObj_inCount_1 = to_unsigned(16#000#, 9) ELSE
      '0';

  
  tmp_8 <= obj_symbolFormationObj_numDataScMinusVecLen WHEN s = '0' ELSE
      tmp_7;

  obj_symbolFormationObj_numDataScMinusVecLen_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_numDataScMinusVecLen <= to_unsigned(16#040#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_numDataScMinusVecLen <= tmp_9;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_numDataScMinusVecLen_reg_process;


  
  tmp_9 <= obj_symbolFormationObj_numDataScMinusVecLen WHEN obj_symbolFormationObj_validInReg = '0' ELSE
      tmp_8;

  tmp_10 <= obj_symbolFormationObj_inCount_1 + to_unsigned(16#001#, 9);

  
  tmp_11 <= tmp_10 WHEN a0 = '0' ELSE
      obj_symbolFormationObj_inCount;

  
  tmp_12 <= obj_symbolFormationObj_inCount_1 WHEN obj_symbolFormationObj_validInReg = '0' ELSE
      tmp_11;

  obj_symbolFormationObj_inCount_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_inCount_1 <= to_unsigned(16#000#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_inCount_1 <= tmp_12;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_inCount_reg_process;


  
  a0 <= '1' WHEN obj_symbolFormationObj_inCount_1 >= tmp_9 ELSE
      '0';

  tmp_13 <=  NOT obj_symbolFormationObj_RAM2WriteSelect;

  
  tmp_14 <= obj_symbolFormationObj_RAM2WriteSelect WHEN a0 = '0' ELSE
      tmp_13;

  
  tmp_15 <= obj_symbolFormationObj_RAM2WriteSelect WHEN obj_symbolFormationObj_validInReg = '0' ELSE
      tmp_14;

  obj_symbolFormationObj_RAM2WriteSelect_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_RAM2WriteSelect <= '0';
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_RAM2WriteSelect <= tmp_15;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_RAM2WriteSelect_reg_process;


  s_1 <= obj_symbolFormationObj_validInReg AND ( NOT obj_symbolFormationObj_RAM2WriteSelect);

  out_rsvd <= '0';

  out_rsvd_1 <= '1';

  
  tmp_16 <= out_rsvd WHEN s_1 = '0' ELSE
      out_rsvd_1;

  obj_symbolFormationObj_writeEnbRAM1_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_writeEnbRAM1 <= '0';
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_writeEnbRAM1 <= tmp_16;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_writeEnbRAM1_reg_process;


  s_2 <= obj_symbolFormationObj_validInReg AND obj_symbolFormationObj_RAM2WriteSelect;

  out_rsvd_2 <= '0';

  out_rsvd_3 <= '1';

  
  tmp_17 <= out_rsvd_2 WHEN s_2 = '0' ELSE
      out_rsvd_3;

  obj_symbolFormationObj_writeEnbRAM2_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_writeEnbRAM2 <= '0';
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_writeEnbRAM2 <= tmp_17;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_writeEnbRAM2_reg_process;


  obj_symbolFormationObj_sym1Done <= '0';

  obj_symbolFormationObj_inCountReg_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_inCountReg <= to_unsigned(16#000#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_inCountReg <= obj_symbolFormationObj_inCount_1;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_inCountReg_reg_process;


  
  a0_1 <= '1' WHEN obj_symbolFormationObj_inCountReg >= obj_symbolFormationObj_numDataScMinusVecLen ELSE
      '0';

  obj_symbolFormationObj_sym1Done_1 <= '1';

  obj_symbolFormationObj_sym2Done <= '0';

  
  a0_2 <= '1' WHEN obj_symbolFormationObj_inCountReg >= obj_symbolFormationObj_numDataScMinusVecLen ELSE
      '0';

  obj_symbolFormationObj_sym2Done_1 <= '1';

  obj_symbolFormationObj_outCount <= to_unsigned(16#000#, 9);

  obj_symbolFormationObj_FFTLenReg_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_FFTLenReg <= to_unsigned(16#040#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_FFTLenReg <= obj_symbolFormationObj_FFTLenRegDelay1;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_FFTLenReg_reg_process;


  tmp_18 <= obj_symbolFormationObj_FFTLenReg - to_unsigned(16#001#, 9);

  
  tmp_19 <= obj_symbolFormationObj_FFTLenMinusVecLen WHEN s = '0' ELSE
      tmp_18;

  
  tmp_20 <= obj_symbolFormationObj_FFTLenMinusVecLen WHEN obj_symbolFormationObj_validInReg = '0' ELSE
      tmp_19;

  obj_symbolFormationObj_FFTLenMinusVecLen_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_FFTLenMinusVecLen <= to_unsigned(16#040#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_FFTLenMinusVecLen <= tmp_20;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_FFTLenMinusVecLen_reg_process;


  obj_symbolFormationObj_startSymbForm <= '0';

  obj_symbolFormationObj_startSymbForm_1 <= '1';

  obj_symbolFormationObj_FFTLenMinusVecLenReg_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_FFTLenMinusVecLenReg <= to_unsigned(16#040#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_FFTLenMinusVecLenReg <= tmp_21;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_FFTLenMinusVecLenReg_reg_process;


  
  s_3 <= '1' WHEN obj_symbolFormationObj_outCount_1 = to_unsigned(16#000#, 9) ELSE
      '0';

  
  tmp_21 <= obj_symbolFormationObj_FFTLenMinusVecLenReg WHEN s_3 = '0' ELSE
      obj_symbolFormationObj_FFTLenMinusVecLen;

  tmp_22 <= obj_symbolFormationObj_outCount_1 + to_unsigned(16#001#, 9);

  
  tmp_23 <= tmp_22 WHEN a0_3 = '0' ELSE
      obj_symbolFormationObj_outCount;

  
  tmp_24 <= obj_symbolFormationObj_outCount_1 WHEN obj_symbolFormationObj_startSymbForm_2 = '0' ELSE
      tmp_23;

  obj_symbolFormationObj_outCount_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_outCount_1 <= to_unsigned(16#000#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_outCount_1 <= tmp_24;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_outCount_reg_process;


  
  a0_3 <= '1' WHEN obj_symbolFormationObj_outCount_1 = tmp_21 ELSE
      '0';

  
  tmp_25 <= obj_symbolFormationObj_startSymbForm_2 WHEN a0_3 = '0' ELSE
      obj_symbolFormationObj_startSymbForm;

  
  tmp_26 <= obj_symbolFormationObj_startSymbForm_2 WHEN obj_symbolFormationObj_startSymbForm_2 = '0' ELSE
      tmp_25;

  
  tmp_28 <= tmp_27 WHEN a0_2 = '0' ELSE
      obj_symbolFormationObj_sym2Done_1;

  
  tmp_29 <= obj_symbolFormationObj_sym2Done_2 WHEN obj_symbolFormationObj_sym2Done_2 = '0' ELSE
      obj_symbolFormationObj_sym2Done;

  
  tmp_31 <= tmp_30 WHEN a0_1 = '0' ELSE
      obj_symbolFormationObj_sym1Done_1;

  
  tmp_32 <= obj_symbolFormationObj_sym1Done_2 WHEN obj_symbolFormationObj_sym1Done_2 = '0' ELSE
      obj_symbolFormationObj_sym1Done;

  
  tmp_30 <= obj_symbolFormationObj_sym1Done_2 WHEN s_4 = '0' ELSE
      tmp_32;

  
  tmp_33 <= tmp_30 WHEN obj_symbolFormationObj_writeEnbRAM1 = '0' ELSE
      tmp_31;

  obj_symbolFormationObj_sym1Done_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_sym1Done_2 <= '0';
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_sym1Done_2 <= tmp_33;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_sym1Done_reg_process;


  
  tmp_34 <= tmp_29 WHEN obj_symbolFormationObj_sym1Done_2 = '0' ELSE
      obj_symbolFormationObj_sym2Done_2;

  
  tmp_27 <= obj_symbolFormationObj_sym2Done_2 WHEN s_4 = '0' ELSE
      tmp_34;

  
  tmp_35 <= tmp_27 WHEN obj_symbolFormationObj_writeEnbRAM2 = '0' ELSE
      tmp_28;

  
  tmp_36 <= tmp_35 WHEN obj_symbolFormationObj_writeEnbRAM1 = '0' ELSE
      tmp_27;

  obj_symbolFormationObj_sym2Done_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_sym2Done_2 <= '0';
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_sym2Done_2 <= tmp_36;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_sym2Done_reg_process;


  s_4 <= (obj_symbolFormationObj_sym2Done_2 OR obj_symbolFormationObj_sym1Done_2) AND ( NOT tmp_26);

  
  tmp_37 <= tmp_26 WHEN s_4 = '0' ELSE
      obj_symbolFormationObj_startSymbForm_1;

  obj_symbolFormationObj_startSymbForm_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_startSymbForm_2 <= '0';
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_startSymbForm_2 <= tmp_37;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_startSymbForm_reg_process;


  obj_symbolFormationObj_startSymbFormReg_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_startSymbFormReg <= '0';
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_startSymbFormReg <= obj_symbolFormationObj_startSymbForm_2;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_startSymbFormReg_reg_process;


  obj_symbolFormationObj_startSymbFormReg2_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_startSymbFormReg2_reg_reg <= (OTHERS => '0');
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_startSymbFormReg2_reg_reg(0) <= obj_symbolFormationObj_startSymbFormReg;
        obj_symbolFormationObj_startSymbFormReg2_reg_reg(1) <= obj_symbolFormationObj_startSymbFormReg2_reg_reg(0);
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_startSymbFormReg2_reg_process;

  obj_symbolFormationObj_startSymbFormReg2 <= obj_symbolFormationObj_startSymbFormReg2_reg_reg(1);

  obj_symbolFormationObj_sendOutput <= '0';

  obj_symbolFormationObj_sendOutput_1 <= '1';

  
  tmp_38 <= obj_symbolFormationObj_sendOutput WHEN obj_symbolFormationObj_startSymbFormReg2 = '0' ELSE
      obj_symbolFormationObj_sendOutput_1;

  obj_symbolFormationObj_sendOutput_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_sendOutput_2 <= '0';
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_sendOutput_2 <= tmp_38;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_sendOutput_reg_process;


  obj_symbolFormationObj_dataOutReg_re <= to_signed(16#000#, 12);
  obj_symbolFormationObj_dataOutReg_im <= to_signed(16#000#, 12);

  obj_symbolFormationObj_outCountReg1_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_outCountReg1_reg_reg <= (OTHERS => to_unsigned(16#000#, 9));
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_outCountReg1_reg_reg(0) <= obj_symbolFormationObj_outCount_1;
        obj_symbolFormationObj_outCountReg1_reg_reg(1) <= obj_symbolFormationObj_outCountReg1_reg_reg(0);
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_outCountReg1_reg_process;

  obj_symbolFormationObj_outCountReg1 <= obj_symbolFormationObj_outCountReg1_reg_reg(1);

  obj_symbolFormationObj_outCountReg2_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_outCountReg2 <= to_unsigned(16#000#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_outCountReg2 <= obj_symbolFormationObj_outCountReg1;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_outCountReg2_reg_process;


  obj_symbolFormationObj_numLgScRegDelay2_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_numLgScRegDelay2 <= to_unsigned(16#006#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_numLgScRegDelay2 <= tmp_2;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_numLgScRegDelay2_reg_process;


  obj_symbolFormationObj_numLgScRegDelay1_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_numLgScRegDelay1 <= to_unsigned(16#006#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_numLgScRegDelay1 <= obj_symbolFormationObj_numLgScRegDelay2;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_numLgScRegDelay1_reg_process;


  obj_symbolFormationObj_numLgScReg_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_numLgScReg <= to_unsigned(16#006#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_numLgScReg <= obj_symbolFormationObj_numLgScRegDelay1;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_numLgScReg_reg_process;


  
  tmp_39 <= obj_symbolFormationObj_numLgScSampled WHEN s = '0' ELSE
      obj_symbolFormationObj_numLgScReg;

  
  tmp_40 <= obj_symbolFormationObj_numLgScSampled WHEN obj_symbolFormationObj_validInReg = '0' ELSE
      tmp_39;

  obj_symbolFormationObj_numLgScSampled_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_numLgScSampled <= to_unsigned(16#006#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_numLgScSampled <= tmp_40;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_numLgScSampled_reg_process;


  obj_symbolFormationObj_numLgScSampledReg_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_numLgScSampledReg <= to_unsigned(16#006#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_numLgScSampledReg <= tmp_41;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_numLgScSampledReg_reg_process;


  
  tmp_41 <= obj_symbolFormationObj_numLgScSampledReg WHEN s_3 = '0' ELSE
      obj_symbolFormationObj_numLgScSampled;

  obj_symbolFormationObj_numLgScOutReg1_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_numLgScOutReg1 <= to_unsigned(16#006#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_numLgScOutReg1 <= tmp_41;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_numLgScOutReg1_reg_process;


  obj_symbolFormationObj_numLgScOutReg2_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_numLgScOutReg2 <= to_unsigned(16#006#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_numLgScOutReg2 <= obj_symbolFormationObj_numLgScOutReg1;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_numLgScOutReg2_reg_process;


  obj_symbolFormationObj_numLgScOutReg3_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_numLgScOutReg3 <= to_unsigned(16#006#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_numLgScOutReg3 <= obj_symbolFormationObj_numLgScOutReg2;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_numLgScOutReg3_reg_process;


  
  a0_4 <= '1' WHEN obj_symbolFormationObj_outCountReg2 < obj_symbolFormationObj_numLgScOutReg3 ELSE
      '0';

  tmp_42 <= obj_symbolFormationObj_numDataSc + obj_symbolFormationObj_numLgScSampled;

  
  tmp_44 <= tmp_43 WHEN s_3 = '0' ELSE
      tmp_42;

  reduced_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        tmp_43 <= to_unsigned(16#000#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        tmp_43 <= tmp_44;
      END IF;
    END IF;
  END PROCESS reduced_process;


  reduced_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        tmp_45 <= to_unsigned(16#000#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        tmp_45 <= tmp_43;
      END IF;
    END IF;
  END PROCESS reduced_1_process;


  
  s_5 <= '1' WHEN obj_symbolFormationObj_outCountReg1 < tmp_45 ELSE
      '0';

  
  tmp_46 <= obj_symbolFormationObj_FFTSampled WHEN s = '0' ELSE
      obj_symbolFormationObj_FFTLenReg;

  
  tmp_47 <= obj_symbolFormationObj_FFTSampled WHEN obj_symbolFormationObj_validInReg = '0' ELSE
      tmp_46;

  obj_symbolFormationObj_FFTSampled_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_FFTSampled <= to_unsigned(16#040#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_FFTSampled <= tmp_47;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_FFTSampled_reg_process;


  obj_symbolFormationObj_numRgScRegDelay2_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_numRgScRegDelay2 <= to_unsigned(16#005#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_numRgScRegDelay2 <= tmp_3;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_numRgScRegDelay2_reg_process;


  obj_symbolFormationObj_numRgScRegDelay1_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_numRgScRegDelay1 <= to_unsigned(16#005#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_numRgScRegDelay1 <= obj_symbolFormationObj_numRgScRegDelay2;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_numRgScRegDelay1_reg_process;


  obj_symbolFormationObj_numRgScReg_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_numRgScReg <= to_unsigned(16#005#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_numRgScReg <= obj_symbolFormationObj_numRgScRegDelay1;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_numRgScReg_reg_process;


  
  tmp_48 <= obj_symbolFormationObj_numRgScSampled WHEN s = '0' ELSE
      obj_symbolFormationObj_numRgScReg;

  
  tmp_49 <= obj_symbolFormationObj_numRgScSampled WHEN obj_symbolFormationObj_validInReg = '0' ELSE
      tmp_48;

  obj_symbolFormationObj_numRgScSampled_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_numRgScSampled <= to_unsigned(16#005#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_numRgScSampled <= tmp_49;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_numRgScSampled_reg_process;


  tmp_50 <= obj_symbolFormationObj_FFTSampled - obj_symbolFormationObj_numRgScSampled;

  obj_symbolFormationObj_FFTLenMinusNumRgScReg_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_FFTLenMinusNumRgScReg <= to_unsigned(16#000#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_FFTLenMinusNumRgScReg <= tmp_51;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_FFTLenMinusNumRgScReg_reg_process;


  
  tmp_51 <= obj_symbolFormationObj_FFTLenMinusNumRgScReg WHEN s_3 = '0' ELSE
      tmp_50;

  
  a0_5 <= '1' WHEN obj_symbolFormationObj_outCount_1 < tmp_41 ELSE
      '0';

  obj_symbolFormationObj_numLgScCountReg <= to_unsigned(16#000#, 9);

  obj_symbolFormationObj_numLgScCountReg_1 <= to_unsigned(16#000#, 9);

  obj_symbolFormationObj_numLgScCount_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_numLgScCount <= to_unsigned(16#006#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_numLgScCount <= obj_symbolFormationObj_numLgScSampled;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_numLgScCount_reg_process;


  tmp_53 <= tmp_52 - to_unsigned(16#001#, 9);

  
  tmp_54 <= '1' WHEN tmp_52 = to_unsigned(16#001#, 9) ELSE
      '0';

  
  tmp_55 <= tmp_53 WHEN tmp_54 = '0' ELSE
      obj_symbolFormationObj_numLgScCountReg;

  
  tmp_57 <= tmp_55 WHEN tmp_56 = '0' ELSE
      obj_symbolFormationObj_numLgScCountReg_1;

  
  tmp_58 <= tmp_52 WHEN a0_5 = '0' ELSE
      tmp_57;

  
  tmp_59 <= tmp_52 WHEN obj_symbolFormationObj_startSymbForm_2 = '0' ELSE
      tmp_58;

  obj_symbolFormationObj_numLgScCountReg_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_numLgScCountReg_2 <= to_unsigned(16#000#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_numLgScCountReg_2 <= tmp_59;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_numLgScCountReg_reg_process;


  
  tmp_52 <= obj_symbolFormationObj_numLgScCountReg_2 WHEN s_3 = '0' ELSE
      obj_symbolFormationObj_numLgScCount;

  
  tmp_56 <= '1' WHEN tmp_52 < to_unsigned(16#001#, 9) ELSE
      '0';

  obj_symbolFormationObj_numSampLeft <= to_unsigned(16#000#, 9);

  obj_symbolFormationObj_numSampLeft_1 <= to_unsigned(16#000#, 9);

  
  tmp_60 <= obj_symbolFormationObj_numSampLeft WHEN tmp_54 = '0' ELSE
      obj_symbolFormationObj_numSampLeft_1;

  obj_symbolFormationObj_insertDC_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_insertDC_1 <= to_unsigned(16#000#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_insertDC_1 <= obj_symbolFormationObj_insertDC;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_insertDC_reg_process;


  
  s_6 <= '1' WHEN obj_symbolFormationObj_insertDC_1 /= to_unsigned(16#000#, 9) ELSE
      '0';

  tmp_61 <= tmp_52 + to_unsigned(16#001#, 9);

  
  tmp_62 <= tmp_52 WHEN s_6 = '0' ELSE
      tmp_61;

  
  tmp_63 <= tmp_60 WHEN tmp_56 = '0' ELSE
      tmp_62;

  
  tmp_64 <= obj_symbolFormationObj_numSampLeft_2 WHEN a0_5 = '0' ELSE
      tmp_63;

  obj_symbolFormationObj_numSampLeft_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_numSampLeft_2 <= to_unsigned(16#000#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_numSampLeft_2 <= tmp_65;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_numSampLeft_reg_process;


  
  tmp_65 <= obj_symbolFormationObj_numSampLeft_2 WHEN obj_symbolFormationObj_startSymbForm_2 = '0' ELSE
      tmp_64;

  tmp_66 <= tmp_51 - tmp_65;

  obj_symbolFormationObj_maxLimitForDataReg_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_maxLimitForDataReg <= to_unsigned(16#000#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_maxLimitForDataReg <= tmp_66;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_maxLimitForDataReg_reg_process;


  obj_symbolFormationObj_maxLimitForDataReg2_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_maxLimitForDataReg2_reg_reg <= (OTHERS => to_unsigned(16#000#, 9));
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_maxLimitForDataReg2_reg_reg(0) <= obj_symbolFormationObj_maxLimitForDataReg;
        obj_symbolFormationObj_maxLimitForDataReg2_reg_reg(1) <= obj_symbolFormationObj_maxLimitForDataReg2_reg_reg(0);
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_maxLimitForDataReg2_reg_process;

  obj_symbolFormationObj_maxLimitForDataReg2 <= obj_symbolFormationObj_maxLimitForDataReg2_reg_reg(1);

  
  s_7 <= '1' WHEN obj_symbolFormationObj_outCountReg1 < obj_symbolFormationObj_maxLimitForDataReg2 ELSE
      '0';

  out_rsvd_4 <= '0';

  out_rsvd_5 <= '0';

  out_rsvd_6 <= '1';

  
  tmp_67 <= out_rsvd_4 WHEN s_7 = '0' ELSE
      out_rsvd_6;

  
  tmp_68 <= out_rsvd_5 WHEN s_5 = '0' ELSE
      tmp_67;

  obj_symbolFormationObj_enbDataPlacing_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_enbDataPlacing <= '0';
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_enbDataPlacing <= tmp_68;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_enbDataPlacing_reg_process;


  obj_symbolFormationObj_sendDC <= '0';

  tmp_69 <= SHIFT_RIGHT(obj_symbolFormationObj_FFTSampled, 1);

  obj_symbolFormationObj_FFTLenBy2_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_FFTLenBy2 <= to_unsigned(16#020#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_FFTLenBy2 <= tmp_69;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_FFTLenBy2_reg_process;


  obj_symbolFormationObj_FFTLenBy2Reg_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_FFTLenBy2Reg <= to_unsigned(16#020#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_FFTLenBy2Reg <= tmp_70;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_FFTLenBy2Reg_reg_process;


  
  tmp_70 <= obj_symbolFormationObj_FFTLenBy2Reg WHEN s_3 = '0' ELSE
      obj_symbolFormationObj_FFTLenBy2;

  obj_symbolFormationObj_FFTLenBy2Reg1_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_FFTLenBy2Reg1 <= to_unsigned(16#020#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_FFTLenBy2Reg1 <= tmp_70;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_FFTLenBy2Reg1_reg_process;


  obj_symbolFormationObj_FFTLenBy2Reg2_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_FFTLenBy2Reg2 <= to_unsigned(16#020#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_FFTLenBy2Reg2 <= obj_symbolFormationObj_FFTLenBy2Reg1;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_FFTLenBy2Reg2_reg_process;


  obj_symbolFormationObj_FFTLenBy2Reg3_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_FFTLenBy2Reg3 <= to_unsigned(16#000#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_FFTLenBy2Reg3 <= obj_symbolFormationObj_FFTLenBy2Reg2;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_FFTLenBy2Reg3_reg_process;


  
  a0_6 <= '1' WHEN (obj_symbolFormationObj_outCountReg2 = obj_symbolFormationObj_FFTLenBy2Reg3) AND (obj_symbolFormationObj_insertDC_1 /= to_unsigned(16#000#, 9)) ELSE
      '0';

  obj_symbolFormationObj_sendDC_1 <= '0';

  obj_symbolFormationObj_sendDC_2 <= '1';

  
  tmp_71 <= obj_symbolFormationObj_sendDC_1 WHEN a0_6 = '0' ELSE
      obj_symbolFormationObj_sendDC_2;

  
  tmp_72 <= obj_symbolFormationObj_sendDC WHEN obj_symbolFormationObj_enbDataPlacing = '0' ELSE
      tmp_71;

  obj_symbolFormationObj_sendDC_3 <= '0';

  
  tmp_73 <= tmp_72 WHEN a0_4 = '0' ELSE
      obj_symbolFormationObj_sendDC_3;

  
  tmp_74 <= obj_symbolFormationObj_sendDC_4 WHEN obj_symbolFormationObj_startSymbFormReg2 = '0' ELSE
      tmp_73;

  obj_symbolFormationObj_sendDC_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_sendDC_4 <= '0';
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_sendDC_4 <= tmp_74;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_sendDC_reg_process;


  obj_symbolFormationObj_FFTLenMinusVecLenReg1_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_FFTLenMinusVecLenReg1 <= to_unsigned(16#040#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_FFTLenMinusVecLenReg1 <= tmp_21;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_FFTLenMinusVecLenReg1_reg_process;


  obj_symbolFormationObj_FFTLenMinusVecLenReg2_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_FFTLenMinusVecLenReg2 <= to_unsigned(16#040#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_FFTLenMinusVecLenReg2 <= obj_symbolFormationObj_FFTLenMinusVecLenReg1;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_FFTLenMinusVecLenReg2_reg_process;


  obj_symbolFormationObj_FFTLenMinusVecLenReg3_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_FFTLenMinusVecLenReg3 <= to_unsigned(16#040#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_FFTLenMinusVecLenReg3 <= obj_symbolFormationObj_FFTLenMinusVecLenReg2;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_FFTLenMinusVecLenReg3_reg_process;


  
  a0_7 <= '1' WHEN obj_symbolFormationObj_outCountReg2 = obj_symbolFormationObj_FFTLenMinusVecLenReg3 ELSE
      '0';

  obj_symbolFormationObj_prevVecSamples <= to_unsigned(16#000#, 9);

  obj_symbolFormationObj_prevVecSamples_1 <= to_unsigned(16#001#, 9);

  obj_symbolFormationObj_numLgScCountReg2_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_numLgScCountReg2_reg_reg <= (OTHERS => to_unsigned(16#000#, 9));
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_numLgScCountReg2_reg_reg(0) <= tmp_52;
        obj_symbolFormationObj_numLgScCountReg2_reg_reg(1) <= obj_symbolFormationObj_numLgScCountReg2_reg_reg(0);
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_numLgScCountReg2_reg_process;

  obj_symbolFormationObj_numLgScCountReg2 <= obj_symbolFormationObj_numLgScCountReg2_reg_reg(1);

  obj_symbolFormationObj_numLgScCountReg3_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_numLgScCountReg3 <= to_unsigned(16#006#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_numLgScCountReg3 <= obj_symbolFormationObj_numLgScCountReg2;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_numLgScCountReg3_reg_process;


  
  a0_8 <= '1' WHEN obj_symbolFormationObj_numLgScCountReg3 < to_unsigned(16#001#, 9) ELSE
      '0';

  obj_symbolFormationObj_prevVecSamples_2 <= to_unsigned(16#000#, 9);

  
  tmp_75 <= obj_symbolFormationObj_prevVecSamples_2 WHEN a0_8 = '0' ELSE
      obj_symbolFormationObj_numLgScCountReg3;

  obj_symbolFormationObj_prevVecSamples_3 <= to_unsigned(16#000#, 9);

  
  tmp_76 <= obj_symbolFormationObj_prevVecSamples_4 WHEN a0_6 = '0' ELSE
      obj_symbolFormationObj_prevVecSamples_1;

  
  tmp_77 <= obj_symbolFormationObj_prevVecSamples WHEN obj_symbolFormationObj_enbDataPlacing = '0' ELSE
      tmp_76;

  
  tmp_78 <= tmp_77 WHEN a0_4 = '0' ELSE
      tmp_75;

  
  tmp_79 <= tmp_78 WHEN a0_7 = '0' ELSE
      obj_symbolFormationObj_prevVecSamples_3;

  
  tmp_80 <= obj_symbolFormationObj_prevVecSamples_4 WHEN obj_symbolFormationObj_startSymbFormReg2 = '0' ELSE
      tmp_79;

  obj_symbolFormationObj_prevVecSamples_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_prevVecSamples_4 <= to_unsigned(16#000#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_prevVecSamples_4 <= tmp_80;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_prevVecSamples_reg_process;


  
  tmp_81 <= obj_symbolFormationObj_prevVecSamples_4 WHEN obj_symbolFormationObj_enbDataPlacing = '0' ELSE
      obj_symbolFormationObj_prevVecSamples_4;

  
  s_8 <= '1' WHEN obj_symbolFormationObj_numLgScCountReg3 = to_unsigned(16#001#, 9) ELSE
      '0';

  obj_symbolFormationObj_dataVec1Samples <= to_unsigned(16#000#, 9);

  obj_symbolFormationObj_dataVec1Samples_1 <= to_unsigned(16#000#, 9);

  
  tmp_82 <= obj_symbolFormationObj_dataVec1Samples WHEN s_8 = '0' ELSE
      obj_symbolFormationObj_dataVec1Samples_1;

  
  tmp_83 <= tmp_82 WHEN a0_8 = '0' ELSE
      obj_symbolFormationObj_numLgScCountReg3;

  
  tmp_84 <= tmp_81 WHEN a0_4 = '0' ELSE
      tmp_83;

  
  tmp_85 <= obj_symbolFormationObj_dataVec1Samples_2 WHEN obj_symbolFormationObj_startSymbFormReg2 = '0' ELSE
      tmp_84;

  obj_symbolFormationObj_dataVec1Samples_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_dataVec1Samples_2 <= to_unsigned(16#000#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_dataVec1Samples_2 <= tmp_85;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_dataVec1Samples_reg_process;


  
  s_9 <= '1' WHEN obj_symbolFormationObj_dataVec1Samples_2 > to_unsigned(16#000#, 9) ELSE
      '0';

  obj_symbolFormationObj_dataVec2_re <= to_signed(16#000#, 12);
  obj_symbolFormationObj_dataVec2_im <= to_signed(16#000#, 12);

  
  s_10 <= '1' WHEN obj_symbolFormationObj_outCount_1 < tmp_44 ELSE
      '0';

  
  s_11 <= '1' WHEN obj_symbolFormationObj_outCount_1 < obj_symbolFormationObj_maxLimitForDataReg ELSE
      '0';

  out_rsvd_7 <= '0';

  out_rsvd_8 <= '0';

  out_rsvd_9 <= '1';

  
  tmp_86 <= out_rsvd_7 WHEN s_11 = '0' ELSE
      out_rsvd_9;

  
  tmp_87 <= out_rsvd_8 WHEN s_10 = '0' ELSE
      tmp_86;

  obj_symbolFormationObj_startRead <= '0';

  obj_symbolFormationObj_startRead_1 <= '1';

  
  tmp_88 <= obj_symbolFormationObj_startRead WHEN tmp_87 = '0' ELSE
      obj_symbolFormationObj_startRead_1;

  obj_symbolFormationObj_startRead_2 <= '0';

  obj_symbolFormationObj_startRead_3 <= '0';

  
  tmp_89 <= obj_symbolFormationObj_startRead_2 WHEN tmp_54 = '0' ELSE
      obj_symbolFormationObj_startRead_3;

  obj_symbolFormationObj_startRead_4 <= '1';

  
  tmp_90 <= tmp_89 WHEN tmp_56 = '0' ELSE
      obj_symbolFormationObj_startRead_4;

  
  tmp_91 <= tmp_88 WHEN a0_5 = '0' ELSE
      tmp_90;

  
  tmp_92 <= obj_symbolFormationObj_startRead_5 WHEN obj_symbolFormationObj_startSymbForm_2 = '0' ELSE
      tmp_91;

  obj_symbolFormationObj_startRead_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_startRead_5 <= '0';
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_startRead_5 <= tmp_92;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_startRead_reg_process;


  obj_symbolFormationObj_startReadFromRAM_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_startReadFromRAM <= '0';
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_startReadFromRAM <= obj_symbolFormationObj_startRead_5;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_startReadFromRAM_reg_process;


  varargin_4_unsigned <= unsigned(varargin_4);

  tmp_93 <= varargin_4_unsigned(8 DOWNTO 0);

  obj_symbolFormationObj_CPLenRegDelay2_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_CPLenRegDelay2 <= to_unsigned(16#010#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_CPLenRegDelay2 <= tmp_93;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_CPLenRegDelay2_reg_process;


  obj_symbolFormationObj_CPLenRegDelay1_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_CPLenRegDelay1 <= to_unsigned(16#010#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_CPLenRegDelay1 <= obj_symbolFormationObj_CPLenRegDelay2;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_CPLenRegDelay1_reg_process;


  obj_symbolFormationObj_CPLenReg_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_CPLenReg <= to_unsigned(16#010#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_CPLenReg <= obj_symbolFormationObj_CPLenRegDelay1;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_CPLenReg_reg_process;


  
  tmp_94 <= obj_symbolFormationObj_CPSampled WHEN s = '0' ELSE
      obj_symbolFormationObj_CPLenReg;

  
  tmp_95 <= obj_symbolFormationObj_CPSampled WHEN obj_symbolFormationObj_validInReg = '0' ELSE
      tmp_94;

  obj_symbolFormationObj_CPSampled_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_CPSampled <= to_unsigned(16#010#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_CPSampled <= tmp_95;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_CPSampled_reg_process;


  obj_symbolFormationObj_CPSampledReg_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_CPSampledReg <= to_unsigned(16#010#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_CPSampledReg <= tmp_96;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_CPSampledReg_reg_process;


  
  tmp_96 <= obj_symbolFormationObj_CPSampledReg WHEN s_3 = '0' ELSE
      obj_symbolFormationObj_CPSampled;

  
  tmp_97 <= '1' WHEN tmp_96 = to_unsigned(16#000#, 9) ELSE
      '0';

  tmp_98 <=  NOT obj_symbolFormationObj_selectRAM;

  
  tmp_99 <= obj_symbolFormationObj_selectRAM WHEN a0_3 = '0' ELSE
      tmp_98;

  
  tmp_100 <= obj_symbolFormationObj_selectRAM WHEN obj_symbolFormationObj_startSymbForm_2 = '0' ELSE
      tmp_99;

  obj_symbolFormationObj_selectRAM_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_selectRAM <= '0';
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_selectRAM <= tmp_100;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_selectRAM_reg_process;


  obj_symbolFormationObj_selectRAMReg_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_selectRAMReg <= '0';
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_selectRAMReg <= obj_symbolFormationObj_selectRAM;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_selectRAMReg_reg_process;


  obj_symbolFormationObj_selectRAMReg1_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_selectRAMReg1 <= '0';
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_selectRAMReg1 <= obj_symbolFormationObj_selectRAMReg;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_selectRAMReg1_reg_process;


  
  tmp_101 <= obj_symbolFormationObj_selectRAMReg1 WHEN tmp_97 = '0' ELSE
      obj_symbolFormationObj_selectRAMReg;

  obj_symbolFormationObj_RAM2ReadSelect_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_RAM2ReadSelect <= '0';
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_RAM2ReadSelect <= tmp_101;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_RAM2ReadSelect_reg_process;


  s_12 <=  NOT obj_symbolFormationObj_RAM2ReadSelect;

  varargin_1_re_signed <= signed(varargin_1_re);

  varargin_1_im_signed <= signed(varargin_1_im);

  obj_symbolFormationObj_dataInReg1_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_dataInReg1_reg_reg_re <= (OTHERS => to_signed(16#000#, 12));
        obj_symbolFormationObj_dataInReg1_reg_reg_im <= (OTHERS => to_signed(16#000#, 12));
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_dataInReg1_reg_reg_im(0) <= varargin_1_im_signed;
        obj_symbolFormationObj_dataInReg1_reg_reg_im(1 TO 3) <= obj_symbolFormationObj_dataInReg1_reg_reg_im(0 TO 2);
        obj_symbolFormationObj_dataInReg1_reg_reg_re(0) <= varargin_1_re_signed;
        obj_symbolFormationObj_dataInReg1_reg_reg_re(1 TO 3) <= obj_symbolFormationObj_dataInReg1_reg_reg_re(0 TO 2);
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_dataInReg1_reg_process;

  obj_symbolFormationObj_dataInReg1_re <= obj_symbolFormationObj_dataInReg1_reg_reg_re(3);
  obj_symbolFormationObj_dataInReg1_im <= obj_symbolFormationObj_dataInReg1_reg_reg_im(3);

  obj_symbolFormationObj_writeAddrRAM2 <= to_unsigned(16#000#, 10);

  tmp_102 <= obj_symbolFormationObj_writeAddrRAM2_1 + to_unsigned(16#001#, 10);

  
  tmp_103 <= tmp_102 WHEN a0_2 = '0' ELSE
      obj_symbolFormationObj_writeAddrRAM2;

  
  tmp_104 <= obj_symbolFormationObj_writeAddrRAM2_1 WHEN obj_symbolFormationObj_writeEnbRAM2 = '0' ELSE
      tmp_103;

  
  tmp_105 <= tmp_104 WHEN obj_symbolFormationObj_writeEnbRAM1 = '0' ELSE
      obj_symbolFormationObj_writeAddrRAM2_1;

  obj_symbolFormationObj_writeAddrRAM2_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_writeAddrRAM2_1 <= to_unsigned(16#000#, 10);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_writeAddrRAM2_1 <= tmp_105;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_writeAddrRAM2_reg_process;


  s_13 <= obj_symbolFormationObj_startRead_5 AND obj_symbolFormationObj_startSymbFormReg;

  obj_symbolFormationObj_readCount <= to_unsigned(16#000#, 9);

  obj_symbolFormationObj_numDataScMinusVecLenReg_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_numDataScMinusVecLenReg <= to_unsigned(16#040#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_numDataScMinusVecLenReg <= tmp_106;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_numDataScMinusVecLenReg_reg_process;


  
  tmp_106 <= obj_symbolFormationObj_numDataScMinusVecLenReg WHEN s_3 = '0' ELSE
      obj_symbolFormationObj_numDataScMinusVecLen;

  tmp_107 <= obj_symbolFormationObj_readCount_1 + to_unsigned(16#001#, 9);

  
  tmp_108 <= tmp_107 WHEN a0_9 = '0' ELSE
      obj_symbolFormationObj_readCount;

  
  tmp_109 <= obj_symbolFormationObj_readCount_1 WHEN s_13 = '0' ELSE
      tmp_108;

  obj_symbolFormationObj_readCount_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_readCount_1 <= to_unsigned(16#000#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_readCount_1 <= tmp_109;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_readCount_reg_process;


  
  a0_9 <= '1' WHEN obj_symbolFormationObj_readCount_1 >= tmp_106 ELSE
      '0';

  obj_symbolFormationObj_readAddr <= to_unsigned(16#000#, 10);

  tmp_110 <= obj_symbolFormationObj_readAddr_1 + to_unsigned(16#001#, 10);

  
  tmp_111 <= tmp_110 WHEN a0_9 = '0' ELSE
      obj_symbolFormationObj_readAddr;

  
  tmp_112 <= obj_symbolFormationObj_readAddr_1 WHEN s_13 = '0' ELSE
      tmp_111;

  obj_symbolFormationObj_readAddr_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_readAddr_1 <= to_unsigned(16#000#, 10);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_readAddr_1 <= tmp_112;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_readAddr_reg_process;


  varargout_1_re_signed <= signed(varargout_1_re_1);

  varargout_1_im_signed <= signed(varargout_1_im_1);

  obj_symbolFormationObj_writeAddrRAM1 <= to_unsigned(16#000#, 10);

  tmp_113 <= obj_symbolFormationObj_writeAddrRAM1_1 + to_unsigned(16#001#, 10);

  
  tmp_114 <= tmp_113 WHEN a0_1 = '0' ELSE
      obj_symbolFormationObj_writeAddrRAM1;

  
  tmp_115 <= obj_symbolFormationObj_writeAddrRAM1_1 WHEN obj_symbolFormationObj_writeEnbRAM1 = '0' ELSE
      tmp_114;

  obj_symbolFormationObj_writeAddrRAM1_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_writeAddrRAM1_1 <= to_unsigned(16#000#, 10);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_writeAddrRAM1_1 <= tmp_115;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_writeAddrRAM1_reg_process;


  varargout_1_re_signed_1 <= signed(varargout_1_re_2);

  varargout_1_im_signed_1 <= signed(varargout_1_im_2);

  
  tmp_re <= varargout_1_re_signed WHEN s_12 = '0' ELSE
      varargout_1_re_signed_1;
  
  tmp_im <= varargout_1_im_signed WHEN s_12 = '0' ELSE
      varargout_1_im_signed_1;

  
  tmp_re_1 <= obj_symbolFormationObj_dataOutRAM_re WHEN obj_symbolFormationObj_startReadFromRAM = '0' ELSE
      tmp_re;
  
  tmp_im_1 <= obj_symbolFormationObj_dataOutRAM_im WHEN obj_symbolFormationObj_startReadFromRAM = '0' ELSE
      tmp_im;

  obj_symbolFormationObj_dataOutRAM_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_dataOutRAM_re <= to_signed(16#000#, 12);
        obj_symbolFormationObj_dataOutRAM_im <= to_signed(16#000#, 12);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_dataOutRAM_re <= tmp_re_1;
        obj_symbolFormationObj_dataOutRAM_im <= tmp_im_1;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_dataOutRAM_reg_process;


  
  tmp_re_2 <= obj_symbolFormationObj_dataVec2_re WHEN obj_symbolFormationObj_enbDataPlacing = '0' ELSE
      obj_symbolFormationObj_dataOutRAM_re;
  
  tmp_im_2 <= obj_symbolFormationObj_dataVec2_im WHEN obj_symbolFormationObj_enbDataPlacing = '0' ELSE
      obj_symbolFormationObj_dataOutRAM_im;

  obj_symbolFormationObj_dataVec2_re_1 <= to_signed(16#000#, 12);
  obj_symbolFormationObj_dataVec2_im_1 <= to_signed(16#000#, 12);

  obj_symbolFormationObj_dataVec2_re_2 <= to_signed(16#000#, 12);
  obj_symbolFormationObj_dataVec2_im_2 <= to_signed(16#000#, 12);

  
  tmp_re_3 <= obj_symbolFormationObj_dataVec2_re_1 WHEN s_8 = '0' ELSE
      obj_symbolFormationObj_dataVec2_re_2;
  
  tmp_im_3 <= obj_symbolFormationObj_dataVec2_im_1 WHEN s_8 = '0' ELSE
      obj_symbolFormationObj_dataVec2_im_2;

  
  tmp_re_4 <= tmp_re_3 WHEN a0_8 = '0' ELSE
      obj_symbolFormationObj_dataOutRAM_re;
  
  tmp_im_4 <= tmp_im_3 WHEN a0_8 = '0' ELSE
      obj_symbolFormationObj_dataOutRAM_im;

  
  tmp_re_5 <= tmp_re_2 WHEN a0_4 = '0' ELSE
      tmp_re_4;
  
  tmp_im_5 <= tmp_im_2 WHEN a0_4 = '0' ELSE
      tmp_im_4;

  
  tmp_re_6 <= obj_symbolFormationObj_dataVec2_re_3 WHEN obj_symbolFormationObj_startSymbFormReg2 = '0' ELSE
      tmp_re_5;
  
  tmp_im_6 <= obj_symbolFormationObj_dataVec2_im_3 WHEN obj_symbolFormationObj_startSymbFormReg2 = '0' ELSE
      tmp_im_5;

  obj_symbolFormationObj_dataVec2_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_dataVec2_re_3 <= to_signed(16#000#, 12);
        obj_symbolFormationObj_dataVec2_im_3 <= to_signed(16#000#, 12);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_dataVec2_re_3 <= tmp_re_6;
        obj_symbolFormationObj_dataVec2_im_3 <= tmp_im_6;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_dataVec2_reg_process;


  obj_symbolFormationObj_prevVecData_re <= to_signed(16#000#, 12);
  obj_symbolFormationObj_prevVecData_im <= to_signed(16#000#, 12);

  
  tmp_re_7 <= obj_symbolFormationObj_prevVecData_re WHEN obj_symbolFormationObj_enbDataPlacing = '0' ELSE
      obj_symbolFormationObj_dataOutRAM_re;
  
  tmp_im_7 <= obj_symbolFormationObj_prevVecData_im WHEN obj_symbolFormationObj_enbDataPlacing = '0' ELSE
      obj_symbolFormationObj_dataOutRAM_im;

  obj_symbolFormationObj_prevVecData_re_1 <= to_signed(16#000#, 12);
  obj_symbolFormationObj_prevVecData_im_1 <= to_signed(16#000#, 12);

  
  tmp_re_8 <= obj_symbolFormationObj_prevVecData_re_1 WHEN a0_8 = '0' ELSE
      obj_symbolFormationObj_dataOutRAM_re;
  
  tmp_im_8 <= obj_symbolFormationObj_prevVecData_im_1 WHEN a0_8 = '0' ELSE
      obj_symbolFormationObj_dataOutRAM_im;

  
  tmp_re_9 <= tmp_re_7 WHEN a0_4 = '0' ELSE
      tmp_re_8;
  
  tmp_im_9 <= tmp_im_7 WHEN a0_4 = '0' ELSE
      tmp_im_8;

  
  tmp_re_10 <= obj_symbolFormationObj_prevVecData_re_2 WHEN obj_symbolFormationObj_startSymbFormReg2 = '0' ELSE
      tmp_re_9;
  
  tmp_im_10 <= obj_symbolFormationObj_prevVecData_im_2 WHEN obj_symbolFormationObj_startSymbFormReg2 = '0' ELSE
      tmp_im_9;

  obj_symbolFormationObj_prevVecData_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_prevVecData_re_2 <= to_signed(16#000#, 12);
        obj_symbolFormationObj_prevVecData_im_2 <= to_signed(16#000#, 12);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_prevVecData_re_2 <= tmp_re_10;
        obj_symbolFormationObj_prevVecData_im_2 <= tmp_im_10;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_prevVecData_reg_process;


  
  tmp_re_11 <= obj_symbolFormationObj_prevVecData_re_2 WHEN obj_symbolFormationObj_enbDataPlacing = '0' ELSE
      obj_symbolFormationObj_prevVecData_re_2;
  
  tmp_im_11 <= obj_symbolFormationObj_prevVecData_im_2 WHEN obj_symbolFormationObj_enbDataPlacing = '0' ELSE
      obj_symbolFormationObj_prevVecData_im_2;

  obj_symbolFormationObj_dataVec1_re <= to_signed(16#000#, 12);
  obj_symbolFormationObj_dataVec1_im <= to_signed(16#000#, 12);

  obj_symbolFormationObj_dataVec1_re_1 <= to_signed(16#000#, 12);
  obj_symbolFormationObj_dataVec1_im_1 <= to_signed(16#000#, 12);

  
  tmp_re_12 <= obj_symbolFormationObj_dataVec1_re WHEN s_8 = '0' ELSE
      obj_symbolFormationObj_dataVec1_re_1;
  
  tmp_im_12 <= obj_symbolFormationObj_dataVec1_im WHEN s_8 = '0' ELSE
      obj_symbolFormationObj_dataVec1_im_1;

  obj_symbolFormationObj_dataVec1_re_2 <= to_signed(16#000#, 12);
  obj_symbolFormationObj_dataVec1_im_2 <= to_signed(16#000#, 12);

  
  tmp_re_13 <= tmp_re_12 WHEN a0_8 = '0' ELSE
      obj_symbolFormationObj_dataVec1_re_2;
  
  tmp_im_13 <= tmp_im_12 WHEN a0_8 = '0' ELSE
      obj_symbolFormationObj_dataVec1_im_2;

  
  tmp_re_14 <= tmp_re_11 WHEN a0_4 = '0' ELSE
      tmp_re_13;
  
  tmp_im_14 <= tmp_im_11 WHEN a0_4 = '0' ELSE
      tmp_im_13;

  
  tmp_re_15 <= obj_symbolFormationObj_dataVec1_re_3 WHEN obj_symbolFormationObj_startSymbFormReg2 = '0' ELSE
      tmp_re_14;
  
  tmp_im_15 <= obj_symbolFormationObj_dataVec1_im_3 WHEN obj_symbolFormationObj_startSymbFormReg2 = '0' ELSE
      tmp_im_14;

  obj_symbolFormationObj_dataVec1_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_dataVec1_re_3 <= to_signed(16#000#, 12);
        obj_symbolFormationObj_dataVec1_im_3 <= to_signed(16#000#, 12);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_dataVec1_re_3 <= tmp_re_15;
        obj_symbolFormationObj_dataVec1_im_3 <= tmp_im_15;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_dataVec1_reg_process;


  
  tmp_re_16 <= obj_symbolFormationObj_dataVec2_re_3 WHEN s_9 = '0' ELSE
      obj_symbolFormationObj_dataVec1_re_3;
  
  tmp_im_16 <= obj_symbolFormationObj_dataVec2_im_3 WHEN s_9 = '0' ELSE
      obj_symbolFormationObj_dataVec1_im_3;

  obj_symbolFormationObj_dataOutReg_re_1 <= to_signed(16#000#, 12);
  obj_symbolFormationObj_dataOutReg_im_1 <= to_signed(16#000#, 12);

  
  tmp_re_17 <= tmp_re_16 WHEN obj_symbolFormationObj_sendDC_4 = '0' ELSE
      obj_symbolFormationObj_dataOutReg_re_1;
  
  tmp_im_17 <= tmp_im_16 WHEN obj_symbolFormationObj_sendDC_4 = '0' ELSE
      obj_symbolFormationObj_dataOutReg_im_1;

  
  tmp_re_18 <= obj_symbolFormationObj_dataOutReg_re WHEN obj_symbolFormationObj_sendOutput_2 = '0' ELSE
      tmp_re_17;
  
  tmp_im_18 <= obj_symbolFormationObj_dataOutReg_im WHEN obj_symbolFormationObj_sendOutput_2 = '0' ELSE
      tmp_im_17;

  obj_symbolFormationObj_dataOut_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_dataOut_reg_reg_re <= (OTHERS => to_signed(16#000#, 12));
        obj_symbolFormationObj_dataOut_reg_reg_im <= (OTHERS => to_signed(16#000#, 12));
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_dataOut_reg_reg_im(0) <= tmp_im_18;
        obj_symbolFormationObj_dataOut_reg_reg_im(1) <= obj_symbolFormationObj_dataOut_reg_reg_im(0);
        obj_symbolFormationObj_dataOut_reg_reg_re(0) <= tmp_re_18;
        obj_symbolFormationObj_dataOut_reg_reg_re(1) <= obj_symbolFormationObj_dataOut_reg_reg_re(0);
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_dataOut_reg_process;

  obj_symbolFormationObj_dataOut_re <= obj_symbolFormationObj_dataOut_reg_reg_re(1);
  obj_symbolFormationObj_dataOut_im <= obj_symbolFormationObj_dataOut_reg_reg_im(1);

  varargout_1_re <= std_logic_vector(obj_symbolFormationObj_dataOut_re);

  varargout_1_im <= std_logic_vector(obj_symbolFormationObj_dataOut_im);

  obj_symbolFormationObj_validOutReg <= '0';

  obj_symbolFormationObj_validOutReg_1 <= '1';

  
  tmp_116 <= obj_symbolFormationObj_validOutReg WHEN obj_symbolFormationObj_sendOutput_2 = '0' ELSE
      obj_symbolFormationObj_validOutReg_1;

  obj_symbolFormationObj_validOut_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_validOut_reg_reg <= (OTHERS => '0');
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_validOut_reg_reg(0) <= tmp_116;
        obj_symbolFormationObj_validOut_reg_reg(1) <= obj_symbolFormationObj_validOut_reg_reg(0);
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_validOut_reg_process;

  obj_symbolFormationObj_validOut <= obj_symbolFormationObj_validOut_reg_reg(1);

  obj_symbolFormationObj_FFTSampledReg_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_FFTSampledReg <= to_unsigned(16#040#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_FFTSampledReg <= tmp_117;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_FFTSampledReg_reg_process;


  
  tmp_117 <= obj_symbolFormationObj_FFTSampledReg WHEN s_3 = '0' ELSE
      obj_symbolFormationObj_FFTSampled;

  obj_symbolFormationObj_FFTLenOutReg1_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_FFTLenOutReg1 <= to_unsigned(16#040#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_FFTLenOutReg1 <= tmp_117;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_FFTLenOutReg1_reg_process;


  obj_symbolFormationObj_FFTLenOutReg2_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_FFTLenOutReg2 <= to_unsigned(16#040#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_FFTLenOutReg2 <= obj_symbolFormationObj_FFTLenOutReg1;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_FFTLenOutReg2_reg_process;


  obj_symbolFormationObj_FFTLenOut_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_FFTLenOut <= to_unsigned(16#040#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_FFTLenOut <= obj_symbolFormationObj_FFTLenOutReg2;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_FFTLenOut_reg_process;


  varargout_3_tmp <= resize(obj_symbolFormationObj_FFTLenOut, 14);

  varargout_3 <= std_logic_vector(varargout_3_tmp);

  obj_symbolFormationObj_CPLenOutReg1_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_CPLenOutReg1 <= to_unsigned(16#010#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_CPLenOutReg1 <= tmp_96;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_CPLenOutReg1_reg_process;


  obj_symbolFormationObj_CPLenOutReg2_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_CPLenOutReg2 <= to_unsigned(16#010#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_CPLenOutReg2 <= obj_symbolFormationObj_CPLenOutReg1;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_CPLenOutReg2_reg_process;


  obj_symbolFormationObj_CPLenOut_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        obj_symbolFormationObj_CPLenOut <= to_unsigned(16#010#, 9);
      ELSIF enb_1_2_0 = '1' THEN
        obj_symbolFormationObj_CPLenOut <= obj_symbolFormationObj_CPLenOutReg2;
      END IF;
    END IF;
  END PROCESS obj_symbolFormationObj_CPLenOut_reg_process;


  varargout_4_tmp <= resize(obj_symbolFormationObj_CPLenOut, 14);

  varargout_4 <= std_logic_vector(varargout_4_tmp);

  varargout_2 <= obj_symbolFormationObj_validOut;

END rtl;

