-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/HDLRx/IEEE_8021513_RX_src_Verify_divide_sizes.vhd
-- Created: 2024-10-27 23:05:38
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: IEEE_8021513_RX_src_Verify_divide_sizes
-- Source Path: HDLRx/full_rx/rx_demodulator_full/channel_estimation_and_equalization/Channel Equalization/equalizer/Real 
-- Divide HDL Optimized/Verify divide size
-- Hierarchy Level: 6
-- Model version: 1.138
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY IEEE_8021513_RX_src_Verify_divide_sizes IS
  PORT( denominator                       :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En12
        numerator                         :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En12
        den                               :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En12
        num                               :   OUT   std_logic_vector(17 DOWNTO 0)  -- sfix18_En12
        );
END IEEE_8021513_RX_src_Verify_divide_sizes;


ARCHITECTURE rtl OF IEEE_8021513_RX_src_Verify_divide_sizes IS

  -- Signals
  SIGNAL denominator_signed               : signed(17 DOWNTO 0);  -- sfix18_En12
  SIGNAL numerator_signed                 : signed(17 DOWNTO 0);  -- sfix18_En12
  SIGNAL den_tmp                          : signed(17 DOWNTO 0);  -- sfix18_En12
  SIGNAL num_tmp                          : signed(17 DOWNTO 0);  -- sfix18_En12

BEGIN
  denominator_signed <= signed(denominator);

  numerator_signed <= signed(numerator);

  -- Verify that the dimensions of the input arrays match, and then reshape
  -- them.
  den_tmp <= denominator_signed;
  num_tmp <= numerator_signed;

  den <= std_logic_vector(den_tmp);

  num <= std_logic_vector(num_tmp);

END rtl;

