-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/HDLTx/IEEE_8021513_TX_src_Sample_Control_Bus_Creator_block1.vhd
-- Created: 2024-10-06 13:51:04
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: IEEE_8021513_TX_src_Sample_Control_Bus_Creator_block1
-- Source Path: HDLTx/full_tx/header_full/h_gen/valid_to_ctrl/Sample Control Bus Creator
-- Hierarchy Level: 4
-- Model version: 4.149
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY IEEE_8021513_TX_src_Sample_Control_Bus_Creator_block1 IS
  PORT( In1                               :   IN    std_logic;
        In2                               :   IN    std_logic;
        In3                               :   IN    std_logic;
        Out1_start                        :   OUT   std_logic;
        Out1_end                          :   OUT   std_logic;
        Out1_valid                        :   OUT   std_logic
        );
END IEEE_8021513_TX_src_Sample_Control_Bus_Creator_block1;


ARCHITECTURE rtl OF IEEE_8021513_TX_src_Sample_Control_Bus_Creator_block1 IS

BEGIN
  Out1_start <= In1;

  Out1_end <= In2;

  Out1_valid <= In3;

END rtl;

