-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/HDLTx/IEEE_8021513_TX_src_psdu_size_to_payload_len.vhd
-- Created: 2024-10-06 13:51:04
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: IEEE_8021513_TX_src_psdu_size_to_payload_len
-- Source Path: HDLTx/full_tx/payload_full/psdu_size_to_payload_len
-- Hierarchy Level: 2
-- Model version: 4.149
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.IEEE_8021513_TX_src_full_tx_pac.ALL;

ENTITY IEEE_8021513_TX_src_psdu_size_to_payload_len IS
  PORT( clk                               :   IN    std_logic;
        reset_x                           :   IN    std_logic;
        enb_1_8_0                         :   IN    std_logic;
        bits_per_subcarrier               :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
        psdu_size                         :   IN    std_logic_vector(23 DOWNTO 0);  -- boolean [24]
        payload_len_in_ofdm_symbols       :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        payload_len_in_words              :   OUT   std_logic_vector(23 DOWNTO 0)  -- ufix24
        );
END IEEE_8021513_TX_src_psdu_size_to_payload_len;


ARCHITECTURE rtl OF IEEE_8021513_TX_src_psdu_size_to_payload_len IS

  -- Signals
  SIGNAL bits_per_subcarrier_unsigned     : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL Delay1_reg                       : vector_of_unsigned4(0 TO 1);  -- ufix4 [2]
  SIGNAL Delay1_out1                      : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL Data_Type_Conversion1_out1       : std_logic_vector(23 DOWNTO 0);  -- ufix1 [24]
  SIGNAL Data_Type_Conversion1_out1_23    : std_logic;  -- ufix1
  SIGNAL Data_Type_Conversion1_out1_22    : std_logic;  -- ufix1
  SIGNAL Data_Type_Conversion1_out1_21    : std_logic;  -- ufix1
  SIGNAL Data_Type_Conversion1_out1_20    : std_logic;  -- ufix1
  SIGNAL Data_Type_Conversion1_out1_19    : std_logic;  -- ufix1
  SIGNAL Data_Type_Conversion1_out1_18    : std_logic;  -- ufix1
  SIGNAL Data_Type_Conversion1_out1_17    : std_logic;  -- ufix1
  SIGNAL Data_Type_Conversion1_out1_16    : std_logic;  -- ufix1
  SIGNAL Data_Type_Conversion1_out1_15    : std_logic;  -- ufix1
  SIGNAL Data_Type_Conversion1_out1_14    : std_logic;  -- ufix1
  SIGNAL Data_Type_Conversion1_out1_13    : std_logic;  -- ufix1
  SIGNAL Data_Type_Conversion1_out1_12    : std_logic;  -- ufix1
  SIGNAL Data_Type_Conversion1_out1_11    : std_logic;  -- ufix1
  SIGNAL Data_Type_Conversion1_out1_10    : std_logic;  -- ufix1
  SIGNAL Data_Type_Conversion1_out1_9     : std_logic;  -- ufix1
  SIGNAL Data_Type_Conversion1_out1_8     : std_logic;  -- ufix1
  SIGNAL Data_Type_Conversion1_out1_7     : std_logic;  -- ufix1
  SIGNAL Data_Type_Conversion1_out1_6     : std_logic;  -- ufix1
  SIGNAL Data_Type_Conversion1_out1_5     : std_logic;  -- ufix1
  SIGNAL Data_Type_Conversion1_out1_4     : std_logic;  -- ufix1
  SIGNAL Data_Type_Conversion1_out1_3     : std_logic;  -- ufix1
  SIGNAL Data_Type_Conversion1_out1_2     : std_logic;  -- ufix1
  SIGNAL Data_Type_Conversion1_out1_1     : std_logic;  -- ufix1
  SIGNAL Data_Type_Conversion1_out1_0     : std_logic;  -- ufix1
  SIGNAL y                                : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL Bit_Shift_out1                   : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL Delay_reg                        : vector_of_unsigned24(0 TO 1);  -- ufix24 [2]
  SIGNAL Delay_out1                       : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL Bit_Shift3_out1                  : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL Bit_Shift5_out1                  : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL Multiport_Switch_out1            : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL Delay3_reg                       : vector_of_unsigned24(0 TO 1);  -- ufix24 [2]
  SIGNAL Delay3_out1                      : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL Gain_cast                        : signed(24 DOWNTO 0);  -- sfix25
  SIGNAL Gain_mul_temp                    : signed(40 DOWNTO 0);  -- sfix41_En15
  SIGNAL Gain_cast_1                      : signed(39 DOWNTO 0);  -- sfix40_En15
  SIGNAL Gain_out1                        : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay2_reg                       : vector_of_unsigned16(0 TO 1);  -- ufix16 [2]
  SIGNAL Delay2_out1                      : unsigned(15 DOWNTO 0);  -- uint16

BEGIN
  -- Get length of the payload expressed in OFDM Symbols:
  -- 
  -- bitsInPsdu = psduSize * 8 * fecRate [bits/payload]
  -- bitsInOFDMSymbol = numDataCarriers * bitsPerSubcarrier [bits/OFDM]
  -- 
  -- payloadLenInOFDMSymbols = ceil( bitsInPsdu / bitsInOFDMSymbol ) [OFDM/payload]
  -- Repetition not supported

  bits_per_subcarrier_unsigned <= unsigned(bits_per_subcarrier);

  Delay1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        Delay1_reg <= (OTHERS => to_unsigned(16#0#, 4));
      ELSIF enb_1_8_0 = '1' THEN
        Delay1_reg(0) <= bits_per_subcarrier_unsigned;
        Delay1_reg(1) <= Delay1_reg(0);
      END IF;
    END IF;
  END PROCESS Delay1_process;

  Delay1_out1 <= Delay1_reg(1);

  Data_Type_Conversion1_out1 <= psdu_size;

  Data_Type_Conversion1_out1_23 <= Data_Type_Conversion1_out1(23);

  Data_Type_Conversion1_out1_22 <= Data_Type_Conversion1_out1(22);

  Data_Type_Conversion1_out1_21 <= Data_Type_Conversion1_out1(21);

  Data_Type_Conversion1_out1_20 <= Data_Type_Conversion1_out1(20);

  Data_Type_Conversion1_out1_19 <= Data_Type_Conversion1_out1(19);

  Data_Type_Conversion1_out1_18 <= Data_Type_Conversion1_out1(18);

  Data_Type_Conversion1_out1_17 <= Data_Type_Conversion1_out1(17);

  Data_Type_Conversion1_out1_16 <= Data_Type_Conversion1_out1(16);

  Data_Type_Conversion1_out1_15 <= Data_Type_Conversion1_out1(15);

  Data_Type_Conversion1_out1_14 <= Data_Type_Conversion1_out1(14);

  Data_Type_Conversion1_out1_13 <= Data_Type_Conversion1_out1(13);

  Data_Type_Conversion1_out1_12 <= Data_Type_Conversion1_out1(12);

  Data_Type_Conversion1_out1_11 <= Data_Type_Conversion1_out1(11);

  Data_Type_Conversion1_out1_10 <= Data_Type_Conversion1_out1(10);

  Data_Type_Conversion1_out1_9 <= Data_Type_Conversion1_out1(9);

  Data_Type_Conversion1_out1_8 <= Data_Type_Conversion1_out1(8);

  Data_Type_Conversion1_out1_7 <= Data_Type_Conversion1_out1(7);

  Data_Type_Conversion1_out1_6 <= Data_Type_Conversion1_out1(6);

  Data_Type_Conversion1_out1_5 <= Data_Type_Conversion1_out1(5);

  Data_Type_Conversion1_out1_4 <= Data_Type_Conversion1_out1(4);

  Data_Type_Conversion1_out1_3 <= Data_Type_Conversion1_out1(3);

  Data_Type_Conversion1_out1_2 <= Data_Type_Conversion1_out1(2);

  Data_Type_Conversion1_out1_1 <= Data_Type_Conversion1_out1(1);

  Data_Type_Conversion1_out1_0 <= Data_Type_Conversion1_out1(0);

  y <= unsigned'(Data_Type_Conversion1_out1_23 & Data_Type_Conversion1_out1_22 & Data_Type_Conversion1_out1_21 & Data_Type_Conversion1_out1_20 & Data_Type_Conversion1_out1_19 & Data_Type_Conversion1_out1_18 & Data_Type_Conversion1_out1_17 & Data_Type_Conversion1_out1_16 & Data_Type_Conversion1_out1_15 & Data_Type_Conversion1_out1_14 & Data_Type_Conversion1_out1_13 & Data_Type_Conversion1_out1_12 & Data_Type_Conversion1_out1_11 & Data_Type_Conversion1_out1_10 & Data_Type_Conversion1_out1_9 & Data_Type_Conversion1_out1_8 & Data_Type_Conversion1_out1_7 & Data_Type_Conversion1_out1_6 & Data_Type_Conversion1_out1_5 & Data_Type_Conversion1_out1_4 & Data_Type_Conversion1_out1_3 & Data_Type_Conversion1_out1_2 & Data_Type_Conversion1_out1_1 & Data_Type_Conversion1_out1_0);

  Bit_Shift_out1 <= y sll 4;

  Delay_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        Delay_reg <= (OTHERS => to_unsigned(16#000000#, 24));
      ELSIF enb_1_8_0 = '1' THEN
        Delay_reg(0) <= Bit_Shift_out1;
        Delay_reg(1) <= Delay_reg(0);
      END IF;
    END IF;
  END PROCESS Delay_process;

  Delay_out1 <= Delay_reg(1);

  Bit_Shift3_out1 <= SHIFT_RIGHT(Delay_out1, 1);

  Bit_Shift5_out1 <= SHIFT_RIGHT(Delay_out1, 4);

  
  Multiport_Switch_out1 <= Delay_out1 WHEN Delay1_out1 = to_unsigned(16#0#, 4) ELSE
      Delay_out1 WHEN Delay1_out1 = to_unsigned(16#1#, 4) ELSE
      Bit_Shift3_out1 WHEN Delay1_out1 = to_unsigned(16#2#, 4) ELSE
      Bit_Shift3_out1 WHEN Delay1_out1 = to_unsigned(16#3#, 4) ELSE
      Bit_Shift5_out1;

  Delay3_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        Delay3_reg <= (OTHERS => to_unsigned(16#000000#, 24));
      ELSIF enb_1_8_0 = '1' THEN
        Delay3_reg(0) <= Multiport_Switch_out1;
        Delay3_reg(1) <= Delay3_reg(0);
      END IF;
    END IF;
  END PROCESS Delay3_process;

  Delay3_out1 <= Delay3_reg(1);

  Gain_cast <= signed(resize(Delay3_out1, 25));
  Gain_mul_temp <= to_signed(16#00A0#, 16) * Gain_cast;
  Gain_cast_1 <= Gain_mul_temp(39 DOWNTO 0);
  Gain_out1 <= unsigned(Gain_cast_1(30 DOWNTO 15)) + ('0' & (Gain_cast_1(14) OR Gain_cast_1(13) OR Gain_cast_1(12) OR Gain_cast_1(11) OR Gain_cast_1(10) OR Gain_cast_1(9) OR Gain_cast_1(8) OR Gain_cast_1(7) OR Gain_cast_1(6) OR Gain_cast_1(5) OR Gain_cast_1(4) OR Gain_cast_1(3) OR Gain_cast_1(2) OR Gain_cast_1(1) OR Gain_cast_1(0)));

  Delay2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        Delay2_reg <= (OTHERS => to_unsigned(16#0000#, 16));
      ELSIF enb_1_8_0 = '1' THEN
        Delay2_reg(0) <= Gain_out1;
        Delay2_reg(1) <= Delay2_reg(0);
      END IF;
    END IF;
  END PROCESS Delay2_process;

  Delay2_out1 <= Delay2_reg(1);

  payload_len_in_ofdm_symbols <= std_logic_vector(Delay2_out1);

  payload_len_in_words <= std_logic_vector(y);

END rtl;

