-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/HDLDecimator/decimator_ip_src_FIR_Decimator.vhd
-- Created: 2024-10-01 07:52:33
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: decimator_ip_src_FIR_Decimator
-- Source Path: HDLDecimator/decimator/FIR Decimator
-- Hierarchy Level: 1
-- Model version: 1.40
-- 
-- HDL FIR Decimation
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY decimator_ip_src_FIR_Decimator IS
  PORT( clk                               :   IN    std_logic;
        reset_x                           :   IN    std_logic;
        enb                               :   IN    std_logic;
        dataIn                            :   IN    std_logic_vector(11 DOWNTO 0);  -- sfix12_En10
        validIn                           :   IN    std_logic;
        softReset                         :   IN    std_logic;
        dataOut                           :   OUT   std_logic_vector(11 DOWNTO 0);  -- sfix12_En10
        validOut                          :   OUT   std_logic
        );
END decimator_ip_src_FIR_Decimator;


ARCHITECTURE rtl OF decimator_ip_src_FIR_Decimator IS

  -- Component Declarations
  COMPONENT decimator_ip_src_FilterBank
    PORT( clk                             :   IN    std_logic;
          reset_x                         :   IN    std_logic;
          enb                             :   IN    std_logic;
          filterIn                        :   IN    std_logic_vector(11 DOWNTO 0);  -- sfix12_En10
          validIn                         :   IN    std_logic;
          softReset                       :   IN    std_logic;
          filterOut                       :   OUT   std_logic_vector(24 DOWNTO 0);  -- sfix25_En22
          filterOut_vld                   :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT decimator_ip_src_FIRDecimInteg
    PORT( clk                             :   IN    std_logic;
          reset_x                         :   IN    std_logic;
          enb                             :   IN    std_logic;
          filterOut                       :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En22
          filterOut_vld                   :   IN    std_logic;
          softReset                       :   IN    std_logic;
          dataOut                         :   OUT   std_logic_vector(11 DOWNTO 0);  -- sfix12_En10
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : decimator_ip_src_FilterBank
    USE ENTITY work.decimator_ip_src_FilterBank(rtl);

  FOR ALL : decimator_ip_src_FIRDecimInteg
    USE ENTITY work.decimator_ip_src_FIRDecimInteg(rtl);

  -- Signals
  SIGNAL filterOut                        : std_logic_vector(24 DOWNTO 0);  -- ufix25
  SIGNAL filterOut_vld                    : std_logic;
  SIGNAL dataOut_tmp                      : std_logic_vector(11 DOWNTO 0);  -- ufix12

BEGIN
  u_FilterBank : decimator_ip_src_FilterBank
    PORT MAP( clk => clk,
              reset_x => reset_x,
              enb => enb,
              filterIn => dataIn,  -- sfix12_En10
              validIn => validIn,
              softReset => softReset,
              filterOut => filterOut,  -- sfix25_En22
              filterOut_vld => filterOut_vld
              );

  u_FirDecimInteg : decimator_ip_src_FIRDecimInteg
    PORT MAP( clk => clk,
              reset_x => reset_x,
              enb => enb,
              filterOut => filterOut,  -- sfix25_En22
              filterOut_vld => filterOut_vld,
              softReset => softReset,
              dataOut => dataOut_tmp,  -- sfix12_En10
              validOut => validOut
              );

  dataOut <= dataOut_tmp;

END rtl;

