-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/HDLRxDemodulator/rx_demod_optimized_src_Verify_divide_sizes.vhd
-- Created: 2024-10-01 18:32:01
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: rx_demod_optimized_src_Verify_divide_sizes
-- Source Path: HDLRxDemodulator/rx_demodulator_full/ofdm_symbol_sync/m_cox/Real Divide HDL Optimized/Verify divide 
-- size
-- Hierarchy Level: 4
-- Model version: 1.64
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY rx_demod_optimized_src_Verify_divide_sizes IS
  PORT( denominator                       :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En24
        numerator                         :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En24
        den                               :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En24
        num                               :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En24
        );
END rx_demod_optimized_src_Verify_divide_sizes;


ARCHITECTURE rtl OF rx_demod_optimized_src_Verify_divide_sizes IS

  -- Signals
  SIGNAL denominator_signed               : signed(31 DOWNTO 0);  -- sfix32_En24
  SIGNAL numerator_signed                 : signed(31 DOWNTO 0);  -- sfix32_En24
  SIGNAL den_tmp                          : signed(31 DOWNTO 0);  -- sfix32_En24
  SIGNAL num_tmp                          : signed(31 DOWNTO 0);  -- sfix32_En24

BEGIN
  denominator_signed <= signed(denominator);

  numerator_signed <= signed(numerator);

  -- Verify that the dimensions of the input arrays match, and then reshape
  -- them.
  den_tmp <= denominator_signed;
  num_tmp <= numerator_signed;

  den <= std_logic_vector(den_tmp);

  num <= std_logic_vector(num_tmp);

END rtl;

